name: 'Save a cache'
description: 'Save Cache artifacts like dependencies and build outputs to improve workflow execution time'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
runs:
  using: 'node20'
  main: '../dist/saveOnly.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
